### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by TatankaConCube**
@vukoye could you please review it and publish as a new dev version

### CODE REVIEW

**Comment by TatankaConCube** [comment]
@vukoye please wait, I found issue on android

**Comment by TatankaConCube** [comment]
@vukoye now lib works, but some users require to update `xml` lib to the latest version, please don't merge this MR till I update `xml` lib

**Comment by TatankaConCube** [comment]
@vukoye now it available for merge

**Comment by aytunch** [comment]
Hi @vukoye 
Can you please take a look at this PR?
It is important for connecty cube which depends on this great lib
Thank you

**Comment by vukoye** [comment]
I merged it, I invited TatankaConCube yesterday, so he can do it without my intervention.

**Comment by TatankaConCube** [comment]
@vukoye thank you for your trust, I didn't have enough time yesterday, will continue this task today

**Pull request merged**
